language: java
jdk:
- oraclejdk8
install: true
sudo: false
# Install mongoDB to perform persistence tests
services:
  - mongodb
  - postgresql
addons:
  postgresql: 9.6
cache:
  directories:
  - $HOME/.m2
  - $HOME/.cache/yarn
# Install semantic-release
before_script:
  - yarn global add @conveyal/maven-semantic-release semantic-release
before_install:
  #- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  # set region in AWS config for S3 setup
  - mkdir ~/.aws && printf '%s\n' '[default]' 'aws_access_key_id=${AWS_ACCESS_KEY_ID}' 'aws_secret_access_key=${AWS_SECRET_ACCESS_KEY}' 'region=us-east-1' > ~/.aws/config
  # create database for e2e tests
  - psql -U postgres -c 'CREATE DATABASE catalogue;'
  # install node v8 for datatools-ui e2e tests
  - nvm install 8
script:
  # run mvn package to make sure unit tests and packaging can work
  - mvn package
  # recursively copy coverage results into another folder so the e2e tests don't overwrite them
  - cp -R target target-unit-test-results
  # run just the e2e tests
  - RUN_E2E=true mvn test
  # recursively copy coverage results into another folder so the deployment results don't overwrite them
  - cp -R target target-e2e-test-results
after_success:
  - semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --use-conveyal-workflow --dev-branch=dev --skip-maven-deploy
  # Run codecov after semantic-release because maven-semantic-release creates extra commits that
  # codecov will need a report on to reference in future PRs to the release branch
  # upload unit test coverage results
  - bash <(curl -s https://codecov.io/bash) -s target-unit-test-results -F unit_tests
  # upload e2e test coverage results
  - bash <(curl -s https://codecov.io/bash) -s target-e2e-test-results -F end_to_end_tests
# notify slack channel of build status
notifications:
  slack: conveyal:WQxmWiu8PdmujwLw4ziW72Gc
before_deploy:
# get branch name of current branch for use in jar name: https://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
# copy packaged jars over to deploy dir
- mkdir deploy
- cp target/dt-*.jar deploy/
- cp "target/dt-$(git describe --always).jar" "deploy/dt-latest-${BRANCH}.jar"
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAIWMAQP5YXWT7OZEA
  secret_access_key:
    secure: cDfIv+/+YimqsH8NvWQZy9YTqaplOwlIeEK+KEBCfsJ3DJK5sa6U4BMZCA4OMP1oTEaIxkd4Rcvj0OAYSFQVNQHtwc+1WeHobzu+MWajMNwmJYdjIvCqMFg2lgJdzCWv6vWcitNvrsYpuXxJlQOirY/4GjEh2gueHlilEdJEItBGYebQL0/5lg9704oeO9v+tIEVivtNc76K5DoxbAa1nW5wCYD7yMQ/cc9EQiMgR5PXNEVJS4hO7dfdDwk2ulGfpwTDrcSaR9JsHyoXj72kJHC9wocS9PLeeYzNAw6ctIymNIjotUf/QUeMlheBbLfTq6DKQ0ISLcD9YYOwviUMEGmnte+HCvTPTtxNbjBWPGa2HMkKsGjTptWu1RtqRJTLy19EN1WG5znO9M+lNGBjLivxHZA/3w7jyfvEU3wvQlzo59ytNMwOEJ3zvSm6r3/QmOr5BU+UHsqy5vv2lOQ9Nv10Uag11zDP1YWCoD96jvjZJsUZtW80ZweHYpDMq0vKdZwZSlbrhgHzS7vlDW7llZPUntz0SfKCjtddbRdy6T4HgsmA8EsBATfisWpmFA6roQSnYwfEZ5ooJ8IMjfOm1qGphrP1Qv8kYkqdtOyTijYErqJ3YzldjeItqaWtyD5tmHm6Wmq6XIbw4bnSfGRx9di+cG5lDEPe1tfBPCf9O5M=
  # upload jars in deploy dir to bucket
  bucket: datatools-builds
  local-dir: deploy
  acl: public_read
  on:
    repo: conveyal/datatools-server
    all_branches: true
