name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        # Set postgres env variables according to test env.yml config
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalogue
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Install node 12 for running e2e tests (and for maven-semantic-release).
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: Setup Maven Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: ~/.m2
          key: maven-local-repo
      - name: Install maven-semantic-release
        # FIXME: Enable cache (add package.json?)
        run: yarn global add @conveyal/maven-semantic-release semantic-release
        # run a script to see if the e2e tests should be ran. This script will set the environment variable SHOULD_RUN_E2E
        # which is used in later travis commands.
        # FIXME: E2E is disabled because it has broken for months. PR to fix e2e should uncomment this line.
      - name: Check if end-to-end tests should run
        run: ./scripts/check-if-e2e-tests-should-run-on-travis.sh
      - name: Add profile credentials to ~/.aws/credentials
        run: ./scripts/add-aws-credentials.sh
      - name: Setup GTFS+ directory (used during testing)
        run: mkdir /tmp/gtfsplus
      - name: Build with Maven (run unit tests)
        run: mvn --no-transfer-progress package
      - name: Restart MongoDB with fresh database (for e2e tests)
        run: ./scripts/restart-mongo-with-fresh-db.sh
      - name: Copy unit test coverage results into another folder # so the e2e tests don't overwrite them
        run: cp -R target target-unit-test-results
      - name: Run e2e tests
        run: if [ "$SHOULD_RUN_E2E" = "true" ]; then RUN_E2E=true mvn test; fi
      - name: Copy e2e coverage results into another folder # so the deployment results don't overwrite them
        run: if [ "$SHOULD_RUN_E2E" = "true" ]; then cp -R target target-e2e-test-results; fi
          # these first codecov runs will upload a report associated with the commit set through CI environment variables
          # use codecov script flags to upload the coverage report for the unit tests
      - name: Upload codecov for unit tests
        run: bash <(curl -s https://codecov.io/bash) -s target-unit-test-results -F unit_tests
      - name: Upload the coverage report for the e2e tests
        run: |
          if [ "$SHOULD_RUN_E2E" = "true" ]; then
          bash <(curl -s https://codecov.io/bash) -s target-e2e-test-results -F end_to_end_tests;
          fi
